[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
publish = false
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
hex = "0.4"
argon2 = "0.5"
ctrlc = "3.4"
rand_core = { version = "0.6", features = ["getrandom"] }
rpassword = "7.4"
rusqlite = { version = "0.40", features = ["backup", "bundled-sqlcipher-vendored-openssl"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sysinfo = "0.37"
thiserror = "2.0"
toml = "0.9"
zeroize = { version = "1.8", features = ["zeroize_derive"] }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
